title: Ryan Amorim | Code Portfolio
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Artist and game developer @ Columbia College Chicago
  <br><br>
  what if you wanted to go to heaven but god said No you're Hardstuck Plat
  <br><br>
  <a href="https://sites.google.com/view/ryanperlatti/home">View My Art Portfolio</a> 
  

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
