title: Ryan Amorim | Code Portfolio
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Artist and game developer @ Columbia College Chicago
  <br><br>
  <a href="https://oakenshoelace.tumblr.com/">Tumblr blog</a> 
  <br><br>
  <a href="https://sites.google.com/view/ryanperlatti/home">View My Art Portfolio</a> 
  <br><br>
  Contact me directly on <a href="https://microsoft.com<perlattisantanna@colum.edu>">Teams</a> or <a href="https://discord.com/users/340161962635952158">Disord</a> 
  

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
